Repository bruvellu/cifonauta, pull requests merged in 2023-10, with the labels that each got.

#228 Feat/keywords relation tags
  meta/forms.py
  meta/migrations/0117_media_tag_life_stage_test.py
  meta/migrations/0118_alter_media_tag_life_stage_test.py
  meta/migrations/0119_alter_media_tag_life_stage_test.py
  meta/migrations/0120_alter_media_tag_life_stage_test.py
  meta/migrations/0121_media_tag_habitat_test_media_tag_life_style_test_and_more.py
  meta/migrations/0122_alter_media_tag_habitat_test_and_more.py
  meta/migrations/0123_rename_tag_habitat_test_media_habitat_and_more.py
  meta/models.py
  meta/signals.py
  meta/views.py
Labels: feature

#230 Fix/small fixes
  media_utils.py
  meta/templates/media_revision_detail.html
  meta/views.py
  user/templates/users/password_reset_email.html
  user/views.py
Labels: fixme

#231 Feat/username recover
  media_utils.py
  meta/views.py
  user/forms.py
  user/models.py
  user/templates/users/forgot_username.html
  user/templates/users/forgot_username_email.html
  user/templates/users/forgot_username_email.txt
  user/templates/users/login.html
  user/urls.py
  user/views.py
Labels: fixme, feature
